version: "3.4"
services:
  storage:
    image: influxdb
    environment: 
        INFLUXDB_DB: load_test
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
         - influxdb-storage:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - storage
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:


    
